### ISSUE TITLE
Copy to TypeScript 

### ISSUE THREAD

**Issue by Poepon** [ygoe/msgpack.js#10]
A compilation exception occurred while trying to copy to a TypeScript file.
The number of parameters of some functions does not correspond.

**Comment by ygoe** [comment]
I have nothing to do with TypeScript so I can't help with that. For a bug report or question in general, your report contains way too little information so there's nothing I can do for now. Please provide more details like code and error messages.

**Comment by ygoe** [comment]
I have removed the `this` argument at the end of the file that was passed to the parameterless anonymous function at the beginning of the file. This might have been the source of your error. Since I have no more details, I'm closing this. Please let me know if you still see the error and be sure to include more details.
