### ISSUE TITLE
Float precision is not kept, leading to a deserialised payload not being equals to the serialised payload.

### ISSUE THREAD

**Issue by mathieucarbou** [ygoe/msgpack.js#36]
I am serialising this:

```
{
  "temp": 3.666667,
  "hum": 25.33,
  "air": 130.667
}
```

bytes: `[131,164,116,101,109,112,202,64,106,170,171,163,104,117,109,202,65,202,163,215,163,97,105,114,202,67,2,170,193]`

deserialising them leads to wrong float values.

```js
window.msgpack.deserialize(new Uint8Array([131,164,116,101,109,112,202,64,106,170,171,163,104,117,109,202,65,202,163,215,163,97,105,114,202,67,2,170,193]));
```

![image](https://github.com/user-attachments/assets/5e95da33-e216-4335-bda7-2548ec99f329)

**Comment by mathieucarbou** [comment]
Note: I get similar issues with msgpack-lite:

![image](https://github.com/user-attachments/assets/e6f72610-ec86-40ef-995a-a64a0fad3e29)

**Comment by ygoe** [comment]
Okay, so what did you expect instead? I cannot find a specific issue in your description.

**Comment by mathieucarbou** [comment]
> Okay, so what did you expect instead? I cannot find a specific issue in your description.

Sorry I thought this was very obvious. I would expect the same behaviour as a standard JSON serialisation / deserialisation:

```js
JSON.stringify({"temp": 3.666667, "hum": 25.33, "air": 130.667 })
// {"temp":3.666667,"hum":25.33,"air":130.667}'

JSON.parse(JSON.stringify({"temp": 3.666667, "hum": 25.33, "air": 130.667 }))
// {temp: 3.666667, hum: 25.33, air: 130.667}
```

Both message pack implementations here and msgpack-lite are not conserving the precision.

The implementation used in most MCU (Arduino and ESP32) from https://arduinojson.org is keeping the exact same json object:

```c++

    JsonDocument doc;
    JsonObject root = doc.to<JsonObject>();
    root["temp"] = temp.value();
    root["hum"] = hum.value();
    root["air"] = air.value();

    // print json doc
    serializeJsonPretty(doc, Serial);
    Serial.println();

    // message pack
    size_t len = measureMsgPack(doc);
    uint8_t* buffer = new uint8_t[len];
    serializeMsgPack(doc, buffer, len);

    // deserialize from binary
    doc.clear();
    deserializeMsgPack(doc, buffer, len);

    // print json doc
    serializeJsonPretty(doc, Serial);
    Serial.println();

    // print buffer
    Serial.print("[");
    for (size_t i = 0; i < len; i++) {
      Serial.print(buffer[i]);
      Serial.print(",");
    }
    Serial.println("]");
```

Here, the output after message pack deserialization is exactly like the input, as we can expect, and which is also consistant with JSON.stringify and JSON.parse.

**Comment by ygoe** [comment]
Hm, there is really not much code involved in this processing. I guess you'd also observe this behaviour with the employed `DataView` API directly. That would be either a browser or a JavaScript specification issue then.

Having said that, floating point number precision is never exact as in the decimal representation. Since the input values are still preserved in their specified precision in the output, I wouldn't see any issue here. If you need to make sure that you preserve the exact decimal representation, you would need to use `decimal` number types like it exists in C# for example. As far as I know JavaScript doesn't know that number type, so you'd need to use strings instead. MessagePack also doesn't know such a type. I guess you can't compare the text representation of serialised JSON with the binary representation of MessagePack then.

**Comment by mathieucarbou** [comment]
That's possible and maybe true.
I don't know enough of the mspack protocol to know how floats are stored, but this might be caused by differences in float representations in languages.

`JSON.stringify(msgpack.encode({"temp": 3.666667, "hum": 25.33, "air": 130.667 }))`

leads to:

`'{"0":131,"1":164,"2":116,"3":101,"4":109,"5":112,"6":203,"7":64,"8":13,"9":85,"10":85,"11":130,"12":18,"13":148,"14":87,"15":163,"16":104,"17":117,"18":109,"19":203,"20":64,"21":57,"22":84,"23":122,"24":225,"25":71,"26":174,"27":20,"28":163,"29":97,"30":105,"31":114,"32":203,"33":64,"34":96,"35":85,"36":88,"37":16,"38":98,"39":77,"40":211}'`

**Comment by mathieucarbou** [comment]
I will close since  probably not related to  a bug in the lib itself.

**Comment by ygoe** [comment]
Actually, a floating point number is stored in MessagePack binary exactly like it's stored in the computer's memory (if I'm not completely mistaken here). So basically, all the bits from that number are copied exactly 1:1 with no modifications. That's part of what makes it so storage-efficient compared to JSON. In JSON, everything is encoded as text, you can see it. I'm not sure how the JSON (de)serialiser handles the number formatting here, because the binary in-memory representation must always be formatted to show it to you in some form (you're not looking at the memory bits, you're looking at a sequence of digit characters).

Maybe that helps a little for understanding what's going on here behind the scenes.
