### ISSUE TITLE
Wrong bin format handling

### ISSUE THREAD

**Issue by qgustavor** [ygoe/msgpack.js#4]
**What is happening:** [during encoding](https://github.com/ygoe/msgpack.js/blob/199fee6e7bf974f398d0731a9f2cc3443e8e5702/msgpack.js#L23-L32) binary data is handled like a plain object and [during decoding](https://github.com/ygoe/msgpack.js/blob/199fee6e7bf974f398d0731a9f2cc3443e8e5702/msgpack.js#L268-L270) it wrongly returns the array which represents the length of the binary data.

**What was expected:** [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) being encoded using the [bin format family](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family) and this format family being decoded back to typed arrays.

Examples:

```javascript
serializeMsgPack(new Uint8Array([1, 2, 3]))
// Expected: new Uint8Array([0xC4, 0x03, 0x01, 0x02, 0x03])
// Got: new Uint8Array([0x83, 0xA1, 0x30, 0x01, 0xA1, 0x31, 0x02, 0xA1, 0x32, 0x03])

deserializeMsgPack(new Uint8Array([0xC4, 0x03, 0x01, 0x02, 0x03]))
// Expected: new Uint8Array([1, 2, 3])
// Got: new Uint8Array([3])
```

**Comment by ygoe** [comment]
Thank you for the report. I can confirm that typed arrays are not converted properly. There are item indices as key names ("0", "1", …) of a map as you describe it. I've done some testing but used "newer" JavaScript features for this. It'll be interesting how all of this runs in IE11.

**Comment by qgustavor** [comment]
I tested some other libraries using RunKit:

* [tiny-msgpack](https://npmjs.com/package/tiny-msgpack) and [msgpack5](https://npmjs.com/package/msgpack5): encodes Uint8Array using the bin format and decodes back to Uint8Arrays. Other typed arrays are encoded like plain objects (like you said "("0", "1", …)") and decoded back to objects.
* [mpack-js](https://npmjs.com/package/mpack-js): encodes typed arrays using the bin format and decodes back to Uint8Arrays.
* [what-the-pack](https://npmjs.com/package/what-the-pack): encodes typed arrays using the bin format and decodes back to Node Buffers.
* [msgpack-lite](https://npmjs.com/package/msgpack-lite): encodes all typed arrays and decoded back to the original formats using [extension types](https://github.com/kawanet/msgpack-lite#extension-types). Node Buffers are encoded and decoded using the bin format.

**Comment by ygoe** [comment]
Thank you for the overview. I think it's most useful to encode Uint8[Clamped]Array to bin and all other TypedArrays to array. bin is then decoded to Uint8Array and array as Array. Those who need a TypedArray instead of a simple Array can convert the entries easily, for example with `new Uint16Array(array)`. No data gets lost this way, just the exact types are a little different. I couldn't imagine what to expect when a Uint16Array is implicitly converted to a Uint8Array. Doubling the number of entries, splitting the WORDs to BYTEs? In which byte order?

Using extension types seems a little inappropriate for anything else than JavaScript-to-JavaScript round-trip encoding. It's certainly incompatible with other platforms and libraries, which I'd like to avoid. It might be added as an option, though, for those who absolutely need type accuracy.

Along the way I could also make deserializing other array types more robust. The fix will be committed in a moment. Fully works in IE11, too.
