### ISSUE TITLE
Any plan to publish to NPM as a module?

### ISSUE THREAD

**Issue by foreseaz** [ygoe/msgpack.js#5]
Nice work, and suggest to add `package.json` and publish to npm as a module for better dependencies management.

**Comment by SaulDoesCode** [comment]
I've got a derivative version of msgpack.js out on npm. [simple-msgpack](https://www.npmjs.com/package/simple-msgpack)

**Comment by foreseaz** [comment]
@SaulDoesCode cool, but I'd recommend the original author to publish his(her) own module, or you could make the PR back to this repo, so that prevent the code conflict or out-sync in future updates.

**Comment by ygoe** [comment]
I don't have any experience with Node.js which is why I haven't created such a package yet. Let's see if I can figure out what I need to do. Now that I know about an example of how it might look like. :-)

@SaulDoesCode You misspelled my GitHub name in your README.md file, the link is correct though.

**Comment by foreseaz** [comment]
@ygoe it's really simple, you can just download [`npm`](https://www.npmjs.com/get-npm), create a `package.json` or merge this [PR](https://github.com/ygoe/msgpack.js/pull/6) in the root folder, and run `npm publish` (may need signup/login npm platform if haven't login before). It's a widely used module management tool for js devs. : )

**Comment by ygoe** [comment]
The npm package is now published. You can find the link in the README file. Have fun!

Please let me know if there are any issues with the package.
